config/routes.rb
Rails.application.routes.draw do
  get 'hello/index'

  get 'hello/login_check'

  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  layout 'application'
  before_action :authenticate_account!, only: :login_check
  def index
    @msg = 'this is sample page.'
  end

  def login_check
    @account = current_account
    @msg = 'account created at: ' + @account.created_at.to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/hello/index.html.erb
<h1 class = "display-4 text-primary">Hello#index</h1>
<p><%= @msg %></p>
<hr>
<div><%= link_to 'login_check page!&gt;&gt;'.html_safe, {action: 'login_check'} %></div>
<div><%= link_to "Sign out&gt;&gt;".html_safe, destroy_account_session_path, method: :delete %></div>

app/views/hello/login_check.html.erb
<h1 class = "display-4 text-primary"><%= @account.email %></h1>
<p><%= @msg %></p>
<hr>
<div><%= link_to '&lt;&lt;go back'.html_safe, {action: 'index'} %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDeviseApp</title>
    <%= csrf_meta_tags %>
    <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>